# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlistitem',
            name='bucketlist',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='items',
            field=models.ManyToManyField(to='bucketlists.BucketListItem'),
        ),
    ]
