# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0002_auto_20160615_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='items',
        ),
        migrations.AddField(
            model_name='bucketlistitem',
            name='bucketlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bucketlists.BucketList'),
        ),
    ]
